@extends('layouts.app')
@section('title', 'Historia de aplazados por departamento | '.config('brand.name'))
@push('styles')<link rel="stylesheet" href="{{ asset('css/education-history.css') }}">@endpush
@section('content')
<div class="edu-history eh-report" id="education-report">
    <header class="eh-report-hero"><div class="eh-wrap"><a href="{{ route('home') }}" class="eh-back">← Volver al inicio</a><span class="eh-eyebrow">Bolivia · Historia educativa</span><h1>Una historia detrás<br>de cada cifra.</h1><p>Aplazados por departamento: 2021–2025 y un escenario posible para 2026.</p><div class="eh-hero-tags"><span>9 departamentos</span><span>5 años de historia</span><span>2026 · estimación</span></div></div></header>
    <div class="eh-wrap">
        <section class="eh-controls" aria-label="Controles del informe">
            <label>Departamento<select id="eh-department">@foreach(array_keys($departmentHistory) as $name)<option value="{{ $name }}" @selected($name==='SANTA CRUZ')>{{ $name === 'POTOSI' ? 'POTOSÍ' : $name }}</option>@endforeach</select></label>
            <label>Ver gráfico en<select id="eh-measure"><option value="total">Cantidad de aplazados</option><option value="tasa">Tasa sobre matrícula (%)</option></select></label>
            <button class="eh-button eh-primary" id="eh-play" type="button">▶ Reproducir años</button><button class="eh-button" id="eh-present" type="button">Modo video</button>
        </section>
        <nav class="eh-year-tabs" aria-label="Seleccionar gestión">@foreach(range(2021,2026) as $year)<button type="button" data-year="{{ $year }}" aria-pressed="false">{{ $year }}@if($year===2026)<small>Proyección</small>@endif</button>@endforeach</nav>
        <section class="eh-focus" aria-live="polite">
            <div class="eh-focus-top"><div><span class="eh-eyebrow" id="eh-status">Datos registrados</span><h2><span id="eh-name">Santa Cruz</span> <span class="eh-focus-year" id="eh-year">2025</span></h2></div><span class="eh-source">Fuente: registros del sistema / Ministerio de Educación</span></div>
            <div class="eh-kpis"><article class="eh-kpi eh-main-kpi"><span>Aplazados en total</span><strong id="eh-total">—</strong><p id="eh-change">Selecciona un año</p></article><article class="eh-kpi"><span>Tasa de aplazados</span><strong id="eh-rate">—</strong><p>Por cada 100 estudiantes matriculados con datos comparables</p></article><article class="eh-kpi"><span>Hombres aplazados</span><strong id="eh-men">—</strong><p id="eh-men-share">—</p></article><article class="eh-kpi"><span>Mujeres aplazadas</span><strong id="eh-women">—</strong><p id="eh-women-share">—</p></article></div>
            <div class="eh-split" aria-label="Distribución de aplazados por sexo"><div id="eh-men-bar"></div><div id="eh-women-bar"></div></div><p id="eh-sex-note" class="eh-note"></p>
            <p id="eh-coverage" class="eh-coverage"></p>
        </section>
        <section class="eh-panel"><div class="eh-heading"><div><span class="eh-eyebrow">2021 → 2026</span><h2>El recorrido de los aplazados</h2></div><div class="eh-legend"><span><i></i> Historia registrada</span><span><i class="eh-estimate"></i> Proyección</span></div></div><div id="eh-chart" class="eh-chart" role="img" aria-label="Gráfico de evolución de aplazados"></div><p class="eh-note">La línea discontinua corresponde a una estimación. Los huecos indican años sin datos. Las cifras exactas están en la tabla.</p></section>
        <section class="eh-panel"><div class="eh-heading"><div><span class="eh-eyebrow">Para comparar con calma</span><h2>Todos los años de <span id="eh-table-name">Santa Cruz</span></h2></div></div><div class="eh-table-scroll"><table class="eh-table"><thead><tr><th>Año</th><th>Aplazados</th><th>Hombres</th><th>Mujeres</th><th>% hombres¹</th><th>% mujeres¹</th><th>Tasa²</th><th>Colegios con reporte</th></tr></thead><tbody id="eh-table-body"></tbody></table></div><p class="eh-note">¹ Proporción entre todos los aplazados, disponible si el desglose por sexo está completo. ² Aplazados ÷ matrícula × 100, solo en colegios con ambos datos del mismo año. No es el porcentaje respecto a toda la población del departamento.</p></section>
        <section class="eh-panel"><span class="eh-eyebrow">Panorama de 2025</span><h2>Los nueve departamentos</h2><p class="eh-note">Selecciona una tarjeta para explorar su historia. Una cantidad mayor no implica una tasa mayor.</p><div class="eh-departments">@foreach($departmentHistory as $name=>$rows)@php($r=$rows[4])<button type="button" data-department="{{ $name }}"><span>{{ $name==='POTOSI'?'POTOSÍ':$name }}</span><strong>{{ $r['total']!==null?number_format($r['total'],0,',','.'):'Sin datos' }}</strong><small>Aplazados · {{ $r['tasa']!==null?number_format($r['tasa'],1,',','.').' % de tasa':'Tasa no disponible' }}</small></button>@endforeach</div></section>
        <details class="eh-method" open><summary>Cómo leer la proyección de 2026</summary><p>Es un escenario orientativo calculado mediante una tendencia lineal de los registros disponibles de 2021–2025. Requiere al menos tres años y datos de 2025. No es una cifra oficial ni una predicción garantizada. No se generan estimaciones cuando falta esa base.</p><p>La tasa proyectada usa tendencias separadas de aplazados y matrícula en los colegios con datos comparables. El reparto por sexo se estima solo con años cuyo desglose está completo y se ajusta al total estimado. No se muestran tasas que superen 100 %. Los cambios en la cantidad de colegios que reportan pueden afectar la tendencia: compara también la cobertura de cada año.</p><p>Este informe utiliza los datos actualmente importados. No consulta ni extrae fichas del Ministerio al abrir la página. Los años pendientes de importación aparecen como “Sin datos”.</p></details>
    </div>
</div>
<script type="application/json" id="eh-data">{!! json_encode($departmentHistory, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE) !!}</script>
@endsection
@push('scripts')<script src="{{ asset('js/education-history.js') }}" defer></script>@endpush
